### ISSUE TITLE
Have not been able to make it work

### ISSUE THREAD

**Issue by kristianmandrup** [sindresorhus/atom-fixmyjs#11]
Have tried installing via apm:

`apm install fixmyjs`

If I go to manage packages I can see it is enabled, however I have not managed to run it on any file.
I tried the Command Palette as mentioned in the docs, but it doesn't seem to appear as an option if I type `fix`. Any suggestions? Should I be able to execute it via Keyboard shortcut or Context menu?
Thanks ;)

**Comment by kristianmandrup** [comment]
Also tried running it as a gulp task:

```js
/*jslint node: true */
'use strict';

var gulp = require('gulp');
var fixmyjs = require('gulp-fixmyjs');

gulp.task('fixjs', function(){
  gulp.src('./apps/_global/data/**/*.js')
    .pipe(fixmyjs({
        // JSHint settings here
    }))
    .pipe(gulp.dest('./apps/_global/data'));
});
```

Any ideas?

```sh
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Error when running fixmyjs:
TypeError: Cannot read property 'type' of null
```

**Comment by sindresorhus** [comment]
Works fine for me with latest Atom. It's excuted through the Command Palette as outlined in the docs.

Not the right place to ask about the gulp task.

**Comment by samuelt1** [comment]
I could not get it to work either. I tried using the command palette as outlined

**Comment by sindresorhus** [comment]
Closing as this plugin is now deprecated.
