### ISSUE TITLE
"command 'extension.fixmyjs' not found on Windows

### ISSUE THREAD

**Issue by Domiii** [sindresorhus/atom-fixmyjs#14]
When running "fixmyjs" through Command Palette, I get the error mentioned in the title:

![image](https://user-images.githubusercontent.com/282899/30773073-9d6d660a-a09b-11e7-8c42-b21ed4374ff7.png)

Running fixmyjs v0.0.2 in Atom v1.16.1 on Windows 7. 

Probably related to other similar issues reported.

**Comment by sindresorhus** [comment]
Closing as this plugin is now deprecated.
